### ISSUE TITLE
Prepare updates for 3.3

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#152]
#### Chapter 4
- [x] New content element - [markdown](https://github.com/contao/core/commit/823bd726beda01c511ca5d4fddf4abc0af6cad98)
- [x] New insert tag flags - [urlencode and rawurlencode](https://github.com/contao/core/commit/c5edd12e07add8fac69844d1d1716efa57789d12)
- [x] [Template inheritance and template insertion](https://github.com/contao/core/commit/2987752222d6458aed2b041d227b482b98ad6c66) (with : #124) https://github.com/contao/docs/commit/f4f81f7c86386c5eb81eb8101b0ecb6333bc38ee
#### Chapter 7
- [ ] New hook - [parseDate](https://github.com/contao/core/commit/3a8b9d91824a1787d82e4b2165e698e82b9a2c52) (see issue #197)
- [ ] New hook - [customizeSearch](https://github.com/contao/core/commit/e77d3fa2b0422086ade6c2c20c3b6ed2fbaa3437) (see issue #194)
- [ ] New hook - [getLanguages](https://github.com/contao/core/commit/0c9b3ac5f17ff57899c65dc225727f5d2adedf9b) (see issue #195)
- [ ] New hook - [colorizeLogEntries](https://github.com/contao/core/commit/b505a7618d376cf310a5f4da47b55858eb6cf93d) (see issue #196)

**Comment by lionel-m** [comment]
@aschempp @leofeyer : I would like to add a paragraph regarding markdown. There are plenty of examples all over the Internet but it's better if we can centralize the documentation in one place.

It is also not necessarily easy for everyone to know that there is an extended version of markdown available in Contao. In the manual, it will be clearly explained.

What do you think ?

**Comment by leofeyer** [comment]
Good idea. You can basically use the GitHub explanation pages as basis:
- https://help.github.com/articles/markdown-basics
- https://help.github.com/articles/github-flavored-markdown

**Comment by lionel-m** [comment]
Perfect, thank you for the links.

**Comment by lionel-m** [comment]
Could you create a branch for 3.3 ?

Thx

**Comment by aschempp** [comment]
Branch is here!

**Comment by lionel-m** [comment]
Thanks
