### ISSUE TITLE
Prepare updates for 3.5

### ISSUE THREAD

**Issue by lionel-m** [contao/docs-archive#251]
- [x] Select multiple checkboxes by holding down the SHIFT key (#7781). (https://github.com/contao/docs/commit/9c12dd9ac3f59f8b826ea6d2e72b5d4dd9c86b6a)
- [x] New front end module "change the password" (#7418). (https://github.com/contao/docs/commit/ee766b2fae138c1befc9df8b785f5b9d483ab619)
- [x] New "picture" insert tag (#7635 and #7718). (https://github.com/contao/docs/commit/9eb5737edd664a79ead5cd2b55cd69783674075b)

**Comment by aschempp** [comment]
Awesome job!

**Comment by lionel-m** [comment]
Thanks :)
